disabled_rules:
  - force_cast
  - function_body_length
  - identifier_name
  - large_tuple
  - nesting
  - multiple_closures_with_trailing_closure

included:
  - Sources
  - Tests

excluded:
  - .build

line_length:
  warning: 180
